spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sinch_db?useSSL=false&serverTimezone=UTC
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: validate # We use Liquibase for schema evolution, not Hibernate!
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: billing-group
      enable-auto-commit: false # Manual offset management
    listener:
      ack-mode: manual
